color <- c('red', 'brown', 'brown', 'green', 'red')
size <- c('small', 'small', 'large', 'small', 'large')
points <- c('yes', 'no', 'yes', 'no', 'no')
edible <- c('toxic', 'edible', 'edible', 'edible', 'edible')
mushrooms <- data.frame(color = color, size = size, points = points, edible = edible)
save(mushrooms, file = "data/mushrooms.rda", compress = "gzip")
